### ISSUE TITLE
Declaring Parameters 

### ISSUE THREAD

**Issue by SharathChandan** [xg590/SX1276#12]
I'd to like to perform FSK modulation on my hardware. it would be great if you show me how i could do that.

**Comment by SharathChandan** [comment]
i guess i should add a new class for FSK to take the required parameters for the fsk mode.

**Comment by xg590** [comment]
In line 95 of current lora.py [https://github.com/xg590/SX1276/blob/8a0d7c4dda34454a5fadb04330c810e2b1990308/lora.py#L95 ](url), we passed an argument  LongRangeMode to register RegOpMode. You can pass another value to RegOpMode to use FSK modulation. However, I have zero knowledge about the operation in FSK mode and it is not what this LoRa library is for.
```
            self.spi_write('RegOpMode', self.Mode['SLEEP'] | 0b0<< 7) # Now it is in FSK mode.
```
By refer to page 93 of the [datasheet](https://github.com/xg590/Learn_SX1276/blob/main/Datasheet.pdf), you know the 7th bit of register RegOpMode is responsible for modulation selection between LoRa and FSK. I cannot help you for further question regrading to FSK modulation. Good Luck

**Comment by SharathChandan** [comment]
fine. i'll try including a class for FSK which takes parameters for a fsk modulation scheme and if it works i'll let you know.

**Comment by SharathChandan** [comment]
what is the maximum speed we can transmit using LoRa some sites tell its programmable upto 300 kbps. what is the maximum rate you have achieved using your library? i am planning to send a larger size data.

**Comment by xg590** [comment]
> what is the maximum speed we can transmit using LoRa some sites tell its programmable upto 300 kbps. what is the maximum rate you have achieved using your library? i am planning to send a larger size data.

You can use the [SX1276/misc/airtime_calculator.zip](https://github.com/xg590/SX1276/blob/main/misc/airtime_calculator.zip) in this repo to estimate the bitrate. Try to play with SF/CR/etc and test the combinations in the field.
