### ISSUE TITLE
RSSI and SNR values

### ISSUE THREAD

**Issue by atonughosh** [xg590/SX1276#14]
Is it possible to display the RSSI and SNR values?

**Comment by xg590** [comment]
the sample code has shown how to get RSSI and SNR values. You override the wanted irq handlers like "brd_packet_handler". See the 23th line of sender.py https://github.com/xg590/SX1276/blob/44cc5a7bb7d42052cdb2de598f1aa790cf744a91/sender/sender.py#L23

**Comment by atonughosh** [comment]
Thank you
