### ISSUE TITLE
RutimeError

### ISSUE THREAD

**Issue by atonughosh** [xg590/SX1276#15]
Hello,

I am trying to send an object over LoRa using your sender and receiver scripts. I am getting a runtime error in line `lora.send(dst_id=0, msg=payload, pkt_type=lora.PKT_TYPE['REQ'])` . 

The error says `RuntimeError: no active exception to reraise`. I have also tried to convert the object to a byte string, 

I get the same error in both cases. I can print the object as a byte string. 

The string is 538 characters long.

What I found out is that when the payload length is getting longer only then the error occurs. Is there any way to send this big payload?

**Comment by atonughosh** [comment]
What I found out is that when the payload length is getting longer only then then error occurs. Is there any way to send this big payload?

**Comment by xg590** [comment]
You get the right explaination for the error. I will add additional info to
the error. Here I want to express my opinion. This library works at the
Data Link Layer so it only care about send the message out and get
acknowledged if the right receiver has it. What you want (payload of
abitrary length) is handled by an upper layer protocol. The 200+ size is
limited by the buffer on the SX1276 chip so you can not stuff the chip
register with larger payload. You have to chop the payload, send them in a
row and reassemble them in order with your own code. This is how network
works.

**Comment by atonughosh** [comment]
Thanks
