### ISSUE TITLE
868 MHz Channels

### ISSUE THREAD

**Issue by atonughosh** [xg590/SX1276#3]
Hello,
The example code has the following lines for the 914-916 MHz and 902-928 HMz.
I would like to modify the following line in the receiver and sender to set the frequency for hopping between 865.20 MHz and 868 MHz. How can I do that?

`channels2Hopping = [914_000_000+200_000 * random.randint(0,10) for i in range(128)] # 914~916 MHz`

`channels2Hopping = [902_300_000+200_000 * random.randint(0,127) for i in range(128)] # 902~928 MHz`

**Comment by xg590** [comment]
I am busy right now. Will give you an example and explanation soon.

**Comment by atonughosh** [comment]
Thank you so much. 
An example would be highly appreciated.
I am stuck at this point.

**Comment by atonughosh** [comment]
> 

The frequencies that my module supports are 865200000, 865500000, 865800000, 866100000, 866400000, 866700000, 867000000, 868000000 Hz

**Comment by atonughosh** [comment]
When I try to set the list manually as `channels2Hopping = [865200000, 865500000, 865800000, 866100000, 866400000, 866700000, 867000000, 868000000]`, 
while receiving, I get the error "**List index out of range**" for **Line Number 364**   
            '''
            (elif irq_flags & self.IrqFlags['FhssChangeChannel']:  
            FhssPresentChannel = self.spi_read('RegHopChannel') 
            Frf = int(self.FHSS_list[FhssPresentChannel] / self.FSTEP)
            self.spi_write('RegFrfMsb', (Frf >> 16) & 0xff))` 
            '''
          of  **lora.py**

**Comment by xg590** [comment]
It may be because your message is too long so the hopping list is used
up. "channels2Hopping" does not mean “supported frequencies” but a
predefined frequencies sequence. Both parties (receiver and
transmitter) need to follow the exact same hopping frequency list.
Each time a transmission succeeds ( IRQ 'FhssChangeChannel' is
triggered), one element is consumed.

**Comment by atonughosh** [comment]
Got it. Thank you so much for the quick reply.

It would be of extreme help if you could provide an example of using the 865.2 MHz to 868 MHz frequency and a bit of explanation so as to modify it later as per requirement.

**Comment by atonughosh** [comment]
Sometimes the following works but most of the time I get **PayloadCrcError**

`channels2Hopping = [867_000_000+200_000 * random.randint(0,5) for i in range(128)] # Both sender and receiver need to know the sequence of frequences they are hopping on before the first hopping operation.`

The following does not work

`channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)] # Both sender and receiver need to know the sequence of frequences they are hopping on before the first hopping operation.`

**Comment by xg590** [comment]
I am free now. 
```
channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)]
```
It seems OK to me. Do you mind share more so I can reproduce the error?

**Comment by atonughosh** [comment]
I am attaching my sender.py and receiver.py files.

Both receiver and sender are set to 

`channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)]`

I am using ESP32 and RFM95W 868 MHz modules.
When I turn on both the receiver and sender, I receive nothing in the receiver. But when I press the reset manually of the sender, only once the data is received instead of continuously receiving the data from the sender as I have added them in an infinite loop.

The output of the receiver is 
`New req packet: b'15267) Hello there, I am Atonu Ghosh. I am testing out frequency Hopping! Does this work? Let us try and check for ourselves!~' 10.75 -36.47
TxDone` 

[https://drive.google.com/drive/folders/1vl-zZ6PVCg9RQRxk-T8eOVQZd-GC8gS-?usp=share_link](url)

Sender.py
```
from machine import Pin
from lora import SX1276
import time, urandom as random


LoRa_MISO_Pin = 12
LoRa_MOSI_Pin = 13
LoRa_SCK_Pin  =  14
LoRa_CS_Pin   = 5
LoRa_RST_Pin  = 27
LoRa_DIO0_Pin = 35
LoRa_DIO1_Pin = 26
LoRa_DIO2_Pin = 25
SPI_CH        =  1

random.seed(11)
channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)] # 914~916 MHz

LoRa_id = 1
lora = SX1276(LoRa_RST_Pin, LoRa_CS_Pin, SPI_CH, LoRa_SCK_Pin, LoRa_MOSI_Pin, LoRa_MISO_Pin, LoRa_DIO0_Pin, LoRa_DIO1_Pin, LoRa_id, channels2Hopping)
lora.after_TxDone = lambda self: print('TxDone')
lora.req_packet_handler = lambda self, packet, SNR, RSSI: print('New req packet:', packet, SNR, RSSI)
lora.brd_packet_handler = lambda self, packet, SNR, RSSI: print('New brd packet:', packet, SNR, RSSI)
while True:
    payload = str(random.randint(100,65536))+") Hello there, I am Atonu Ghosh. I am testing out frequency Hopping! Does this work? Let us try and check for ourselves!~"
    print(payload)
    lora.send(dst_id=0, msg=payload, flags=lora.FLAG['REQ']) # Sender's lora_id is 1 and receiver's is 0
```

Receiver.py
```
from machine import Pin
from lora import SX1276
import time, urandom as random

LoRa_MISO_Pin = 12
LoRa_MOSI_Pin = 13
LoRa_SCK_Pin  =  14
LoRa_CS_Pin   = 5
LoRa_RST_Pin  = 27
LoRa_DIO0_Pin = 35
LoRa_DIO1_Pin = 26
LoRa_DIO2_Pin = 25
SPI_CH        =  1

random.seed(11)
channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)] # Both sender and receiver need to know the sequence of frequences they are hopping on before the first hopping operation.

LoRa_id = 0
lora = SX1276(LoRa_RST_Pin, LoRa_CS_Pin, SPI_CH, LoRa_SCK_Pin, LoRa_MOSI_Pin, LoRa_MISO_Pin, LoRa_DIO0_Pin, LoRa_DIO1_Pin, LoRa_id, channels2Hopping)
lora.after_TxDone = lambda self: print('TxDone')
lora.req_packet_handler = lambda self, packet, SNR, RSSI: print('New req packet:', packet, SNR, RSSI)
lora.brd_packet_handler = lambda self, packet, SNR, RSSI: print('New brd packet:', packet, SNR, RSSI)
lora.mode = 'RXCONTINUOUS'

while True:
    time.sleep(0.1)
```

**Comment by xg590** [comment]
Sorry for the late reply but I am still working on related problems.

**Comment by atonughosh** [comment]
> Sorry for the late reply but I am still working on related problems.

No problem. 
Could you please help me with broadcasting a message to all the nodes?
255 should broadcast a message to all the receiver nodes, but it does not work. Only a node that is set to have the address 255 receives the message.

**Comment by xg590** [comment]
Hi [atonughosh](https://github.com/atonughosh), I have fixed several bugs so you can follow the [new sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py) and modify your send.py/recv.py code accordingly. I have tried your code after minor modification and get the wanted result. <br/>
Regarding the broadcasting, you can use the augment "pkt_type" of function "send". Then, every node would receive it. <br/>
```
lora.send(dst_id=3, msg=payload, pkt_type=lora.PKT_TYPE['BRD'])
```
Yes, I did not use "broadcast address" to indicates the packet type because we can have more than 256 LoRa modems in the same network otherwise.  <br/>
Looking to hear from you about your test result. <br/>
PS: I have to confess. I was not familiar with the code anymore just days ago and this is why it takes me days to fix the bugs. Anyway. Cheers.

**Comment by atonughosh** [comment]
> Hi [atonughosh](https://github.com/atonughosh), I have fixed several bugs so you can follow the [new sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py) and modify your send.py/recv.py code accordingly. I have tried your code after minor modification and get the wanted result. Regarding the broadcasting, you can use the augment "pkt_type" of function "send". Then, every node would receive it.
> 
> ```
> lora.send(dst_id=3, msg=payload, pkt_type=lora.PKT_TYPE['BRD'])
> ```
> 
> Yes, I did not use "broadcast address" to indicates the packet type because we can have more than 256 LoRa modems in the same network otherwise. Looking to hear from you about your test result. PS: I have to confess. I was not familiar with the code anymore just days ago and this is why it takes me days to fix the bugs. Anyway. Cheers.

Thank you so much for the effort. I will implement the code and update you on this very soon.

**Comment by atonughosh** [comment]
> Hi [atonughosh](https://github.com/atonughosh), I have fixed several bugs so you can follow the [new sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py) and modify your send.py/recv.py code accordingly. I have tried your code after minor modification and get the wanted result. Regarding the broadcasting, you can use the augment "pkt_type" of function "send". Then, every node would receive it.
> 
> ```
> lora.send(dst_id=3, msg=payload, pkt_type=lora.PKT_TYPE['BRD'])
> ```
> 
> Yes, I did not use "broadcast address" to indicates the packet type because we can have more than 256 LoRa modems in the same network otherwise. Looking to hear from you about your test result. PS: I have to confess. I was not familiar with the code anymore just days ago and this is why it takes me days to fix the bugs. Anyway. Cheers.

It works fine, but the packet gets jumbled up when sent too quickly. Else, works fabulously. Thanks again.

**Comment by xg590** [comment]
Cheers ~~~

**Comment by xg590** [comment]
> > Hi [atonughosh](https://github.com/atonughosh), I have fixed several bugs so you can follow the [new sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py) and modify your send.py/recv.py code accordingly. I have tried your code after minor modification and get the wanted result. Regarding the broadcasting, you can use the augment "pkt_type" of function "send". Then, every node would receive it.
> > ```
> > lora.send(dst_id=3, msg=payload, pkt_type=lora.PKT_TYPE['BRD'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yes, I did not use "broadcast address" to indicates the packet type because we can have more than 256 LoRa modems in the same network otherwise. Looking to hear from you about your test result. PS: I have to confess. I was not familiar with the code anymore just days ago and this is why it takes me days to fix the bugs. Anyway. Cheers.
> 
> It works fine, but the packet gets jumbled up when sent too quickly. Else, works fabulously. Thanks again.

If only one LoRa modem is transmitting, I guess it is the "print-out" strings that mix up. It is because we are using print function in an IRQ handler (It is debugging). The variable "packet" should be intact.

**Comment by atonughosh** [comment]
> > > Hi [atonughosh](https://github.com/atonughosh), I have fixed several bugs so you can follow the [new sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py) and modify your send.py/recv.py code accordingly. I have tried your code after minor modification and get the wanted result. Regarding the broadcasting, you can use the augment "pkt_type" of function "send". Then, every node would receive it.
> > > ```
> > > lora.send(dst_id=3, msg=payload, pkt_type=lora.PKT_TYPE['BRD'])
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Yes, I did not use "broadcast address" to indicates the packet type because we can have more than 256 LoRa modems in the same network otherwise. Looking to hear from you about your test result. PS: I have to confess. I was not familiar with the code anymore just days ago and this is why it takes me days to fix the bugs. Anyway. Cheers.
> > 
> > 
> > It works fine, but the packet gets jumbled up when sent too quickly. Else, works fabulously. Thanks again.
> 
> If only one LoRa modem is transmitting, I guess it is the "print-out" strings that mix up. It is because we are using print function in an IRQ handler (It is debugging). The variable "packet" should be intact.

Thank you, I'll try printing the packet.

**Comment by xg590** [comment]
I mean you can declare a variable (attribute) in the class and change the variable (do not print it) in the IRQ handler. Then you print it in the main thread. Do not use print in an IRQ handler unless you know what you are doing. Print function takes too much time to execute and will disrupt the IRQ process.
