### ISSUE TITLE
How to fetch the source ID of the sender?

### ISSUE THREAD

**Issue by atonughosh** [xg590/SX1276#4]
How to fetch the source ID (ID of the sender of the message) from a received packet? 

Can we do something like
` `def onBroadcast(self, packet, SNR, RSSI):
    print("[New 'Discovery' packet]", src_id, packet, SNR, RSSI)``

**Comment by atonughosh** [comment]
> How to fetch the source ID (ID of the sender of the message) from a received packet?
> 
> Can we do something like ` `def onBroadcast(self, packet, SNR, RSSI): print("[New 'Discovery' packet]", src_id, packet, SNR, RSSI)``

I modified line number 351 to `self.brd_packet_handler(None, data, src_id, SNR, RSSI)` and now I can have the src_id.

**Comment by xg590** [comment]
> > How to fetch the source ID (ID of the sender of the message) from a received packet?
> > Can we do something like ` `def onBroadcast(self, packet, SNR, RSSI): print("[New 'Discovery' packet]", src_id, packet, SNR, RSSI)``
> 
> I modified line number 351 to `self.brd_packet_handler(None, data, src_id, SNR, RSSI)` and now I can have the src_id.

That is right. 
BTW, can you do me a favor and star this repo. I want more people to see it. :)

**Comment by atonughosh** [comment]
> > > How to fetch the source ID (ID of the sender of the message) from a received packet?
> > > Can we do something like ` `def onBroadcast(self, packet, SNR, RSSI): print("[New 'Discovery' packet]", src_id, packet, SNR, RSSI)``
> > 
> > 
> > I modified line number 351 to `self.brd_packet_handler(None, data, src_id, SNR, RSSI)` and now I can have the src_id.
> 
> That is right. BTW, can you do me a favor and star this repo. I want more people to see it. :)

Sure

**Comment by atonughosh** [comment]
The following code boardcasts "Hello". The receiver send "REQ" reply. But the REQ is not received.
```from machine import Pin
from lora import SX1276
import time, urandom as random


# Heltec WiFi LoRa 32 V2
LoRa_MISO_Pin = 12
LoRa_MOSI_Pin = 13
LoRa_SCK_Pin  =  14
LoRa_CS_Pin   = 5
LoRa_RST_Pin  = 27
LoRa_DIO0_Pin = 35
LoRa_DIO1_Pin = 26
LoRa_DIO2_Pin = 25
SPI_CH        =  1

LoRa_id = 1
node_type = "BS"


random.seed(11)
channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)] # 914~916 MHz
# channels2Hopping = [902_300_000+200_000 * random.randint(0,127) for i in range(128)] # 902~928 MHz


lora = SX1276(LoRa_RST_Pin, LoRa_CS_Pin, SPI_CH, LoRa_SCK_Pin, LoRa_MOSI_Pin, LoRa_MISO_Pin, LoRa_DIO0_Pin, LoRa_DIO1_Pin, LoRa_id, channels2Hopping)
lora.req_packet_handler = lambda self, packet, SNR, RSSI: print("[New 'REQ' packet]", packet, SNR, RSSI)
lora.brd_packet_handler = lambda self, packet, SNR, RSSI: print("[New 'BRD' packet]", packet, SNR, RSSI)
lora.mode = 'RXCONTINUOUS'


payload = "Hello"
print(payload)
lora.send(dst_id=0, msg=payload, pkt_type=lora.PKT_TYPE['BRD']) # Sender's lora_id is 1 and receiver's is 0
lora.mode = 'RXCONTINUOUS'

while True: 
    time.sleep(0.1)

```

The receiver that replies is as under -  Tried with both ```lora.mode = 'STANDBY'``` and ```lora.mode = 'TX'```

```
from machine import Pin
from lora import SX1276
import time, urandom as random


# Heltec WiFi LoRa 32 V2
LoRa_MISO_Pin = 12
LoRa_MOSI_Pin = 13
LoRa_SCK_Pin  =  14
LoRa_CS_Pin   = 5
LoRa_RST_Pin  = 27
LoRa_DIO0_Pin = 35
LoRa_DIO1_Pin = 26
LoRa_DIO2_Pin = 25
SPI_CH        =  1

LoRa_id = 0
node_type = "BS"


def onBroadcast(self, packet, src_id, SNR, RSSI):
    lora.mode = 'TX'
    time.sleep(3)
    print("[New 'Discovery' packet from]", src_id)
    if packet.decode("utf-8") == "Hello":
        if node_type == "BS" or node_type == "HS":
            payload = str({"node_id": "1", "node_type":"BS"})
            print("Sending discovery reply")
            print(payload)
            lora.send(dst_id=1, msg="test message reply", pkt_type=lora.PKT_TYPE['REQ']) # A broadcast request. Do not expect respond.
    lora.mode = 'RXCONTINUOUS'

random.seed(11)
channels2Hopping = [866_000_000+200_000 * random.randint(0,10) for i in range(128)] # 914~916 MHz
# channels2Hopping = [902_300_000+200_000 * random.randint(0,127) for i in range(128)] # 902~928 MHz


lora = SX1276(LoRa_RST_Pin, LoRa_CS_Pin, SPI_CH, LoRa_SCK_Pin, LoRa_MOSI_Pin, LoRa_MISO_Pin, LoRa_DIO0_Pin, LoRa_DIO1_Pin, LoRa_id, channels2Hopping)
lora.req_packet_handler = lambda self, packet, SNR, RSSI: print("[New 'REQ' packet]", packet, SNR, RSSI)
lora.brd_packet_handler = onBroadcast
lora.mode = 'RXCONTINUOUS'

while True:
    time.sleep(0.1)
```

**Comment by xg590** [comment]
I suggest you inspect the driver code and learn how it works before modification. Your current code indicates you misunderstand some basic concepts in low-level communication<br/>
Typically, broadcast is a one-way communication, so I created two different packet types: One is broadcast packet (BRD) and one is request-acknowledgement (REQ) packet. Every node will receive every packet. It is the receiver's job to discard it or respond it regardless of the packet type. <br/>
Why boardcast is a one-way comm? Because the receivers cannot reply simultaneously and flood the radio channel with packets. These radio wave can and will interfere. <br/>
I guess you want a specific receiver to respond a packet from the sender and this is exactly what has been demonstrated in the [sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py).
```
Line 28: lora.send(dst_id=0, msg=payload, pkt_type=lora.PKT_TYPE['REQ']) # Sender's lora_id is 1 and receiver's is 0
```  
The sample code means our sender (lora_id=1) is trying to send a packet to one specific receiver (lora_id=0) and ask the special receiver to respond. <br/>
But actually, the sender transmits a packet via radio wave and every receiver gets the packet (the sender switches to receive mode and wait for a response). But only one receiver (lora_id=0) knows the packet is for me (by matching packet's dst_id with its own src_id) and I (the receiver) will send back an "ACK" packet to everyone (including the listening sender). The sender gets the "ACK" and switches back to "STANDBY" mode. Other SX1276 modems also receives the "REQ" packet from sender and "ACK" from the receiver but they do nothing.

**Comment by atonughosh** [comment]
> I suggest you inspect the driver code and learn how it works before modification. Your current code indicates you misunderstand some basic concepts in low-level communication Typically, broadcast is a one-way communication, so I created two different packet types: One is broadcast packet (BRD) and one is request-acknowledgement (REQ) packet. Every node will receive every packet. It is the receiver's job to discard it or respond it regardless of the packet type. Why boardcast is a one-way comm? Because the receivers cannot reply simultaneously and flood the radio channel with packets. These radio wave can and will interfere. I guess you want a specific receiver to respond a packet from the sender and this is exactly what has been demonstrated in the [sample code](https://github.com/xg590/SX1276/blob/1f9135a333adbb5e7411ad7023e78d4a502e28ec/sender/sender.py).
> 
> ```
> Line 28: lora.send(dst_id=0, msg=payload, pkt_type=lora.PKT_TYPE['REQ']) # Sender's lora_id is 1 and receiver's is 0
> ```
> 
> The sample code means our sender (lora_id=1) is trying to send a packet to one specific receiver (lora_id=0) and ask the special receiver to respond. But actually, the sender transmits a packet via radio wave and every receiver gets the packet (the sender switches to receive mode and wait for a response). But only one receiver (lora_id=0) knows the packet is for me (by matching packet's dst_id with its own src_id) and I (the receiver) will send back an "ACK" packet to everyone (including the listening sender). The sender gets the "ACK" and switches back to "STANDBY" mode. Other SX1276 modems also receives the "REQ" packet from sender and "ACK" from the receiver but they do nothing.

Actually, I am trying to establish bi-directional communication. A sender either broadcasts or sends a "REQ" packet. The receiver reads the data, and based on the packet content, the receiver replies. Example: One node, either "BRD" or "REQ," a "Hello", the receiver reads the "Hello" and responds with a "Hi" only if "Hello" is received by it.

**Comment by xg590** [comment]
Then you must know how to switch modes to do two-way comm. The current lib
is actually doing two way comm. You remember that the req packet is
received by the receiver and the ack packet is received by the sender. Now
the ack is empty but you can fill something in the packet. <br/>.
I am going to defense my thesis next thursday so this weekend is not a good
time for me to implement a two-way comm scheme. You can fork the repo and
implement it . I am happy to  merge it. Or I can do it next weekend.

**Comment by atonughosh** [comment]
> Then you must know how to switch modes to do two-way comm. The current lib is actually doing two way comm. You remember that the req packet is received by the receiver and the ack packet is received by the sender. Now the ack is empty but you can fill something in the packet. <br/>. I am going to defense my thesis next thursday so this weekend is not a good time for me to implement a two-way comm scheme. You can fork the repo and implement it . I am happy to merge it. Or I can do it next weekend.
> […](#)
> On Sun, Nov 27, 2022 at 01:32 ATONU GHOSH ***@***.***> wrote: I suggest you inspect the driver code and learn how it works before modification. Your current code indicates you misunderstand some basic concepts in low-level communication Typically, broadcast is a one-way communication, so I created two different packet types: One is broadcast packet (BRD) and one is request-acknowledgement (REQ) packet. Every node will receive every packet. It is the receiver's job to discard it or respond it regardless of the packet type. Why boardcast is a one-way comm? Because the receivers cannot reply simultaneously and flood the radio channel with packets. These radio wave can and will interfere. I guess you want a specific receiver to respond a packet from the sender and this is exactly what has been demonstrated in the sample code <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xg590_SX1276_blob_1f9135a333adbb5e7411ad7023e78d4a502e28ec_sender_sender.py&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=68-jaezqLTx9tGFv4ExwCQ&m=jFhvzPQL5sdDJx3ooxAxSPtXgsub7vOpLk4C0tzH6vW3HdH1qDOOvE6XnhfRg8OA&s=M23s9nAmRHddFiONdqt5B0_GqO319FRAj81YkZ0H2OE&e=> . Line 28: lora.send(dst_id=0, msg=payload, pkt_type=lora.PKT_TYPE['REQ']) # Sender's lora_id is 1 and receiver's is 0 The sample code means our sender (lora_id=1) is trying to send a packet to one specific receiver (lora_id=0) and ask the special receiver to respond. But actually, the sender transmits a packet via radio wave and every receiver gets the packet (the sender switches to receive mode and wait for a response). But only one receiver (lora_id=0) knows the packet is for me (by matching packet's dst_id with its own src_id) and I (the receiver) will send back an "ACK" packet to everyone (including the listening sender). The sender gets the "ACK" and switches back to "STANDBY" mode. Other SX1276 modems also receives the "REQ" packet from sender and "ACK" from the receiver but they do nothing. Actually, I am trying to establish bi-directional communication. A sender either broadcasts or sends a "REQ" packet. The receiver reads the data, and based on the packet content, the receiver replies. Example: One node, either "BRD" or "REQ," a "Hello", the receiver reads the "Hello" and responds with a "Hi" only if "Hello" is received by it. — Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xg590_SX1276_issues_4-23issuecomment-2D1328181441&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=68-jaezqLTx9tGFv4ExwCQ&m=jFhvzPQL5sdDJx3ooxAxSPtXgsub7vOpLk4C0tzH6vW3HdH1qDOOvE6XnhfRg8OA&s=ZUnSe-9TfS8ZoC3yfDh4MLUVgbqMDuaTfpMVEEU5ZNY&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKJHY6FFIZ2JWFTUSVFZKBLWKL6BLANCNFSM6AAAAAASMJLR3A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=68-jaezqLTx9tGFv4ExwCQ&m=jFhvzPQL5sdDJx3ooxAxSPtXgsub7vOpLk4C0tzH6vW3HdH1qDOOvE6XnhfRg8OA&s=P7PZcRCMq7D64igHCpAouaP1JjB_1s8gT9tr-AUKU3E&e=> . You are receiving this because you commented.Message ID: ***@***.***>

Sure, will do the development after forking it. All the best for your exam.
