### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by antirez** [xg590/SX1276#9]
Hi, thank you for writing this code. I look forward to use it as a base for my LYLIGO Lora board. However I can't find any licensing information. Please could you tell me with what license do you release this code? I want to use it according to your wishes. Cheers.

**Comment by antirez** [comment]
I saw the other repository you created to learn how the chip works. I just want to say a big thank you, because that work is *awesome*. A lot of details, step by step comments to see what we are doing with the chip. That's totally great. Thanks :)

**Comment by xg590** [comment]
> Hi, thank you for writing this code. I look forward to use it as a base for my LYLIGO Lora board. However I can't find any licensing information. Please could you tell me with what license do you release this code? I want to use it according to your wishes. Cheers.

If you're not using it for commercial purposes, you can do whatever you want. I would wish you mention my contribution in acknowledgment section if this is used in a research project.

**Comment by antirez** [comment]
Thanks! Appreciated :)

**Comment by xg590** [comment]
> I saw the other repository you created to learn how the chip works. I just want to say a big thank you, because that work is *awesome*. A lot of details, step by step comments to see what we are doing with the chip. That's totally great. Thanks :)

Thanks for your compliment.
